export default function ReportsPage() {
  return (
    <main>
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-800">
          Reports
        </h1>

        <p className="text-gray-500 mt-1">
          View and analyze HRMS reports
        </p>
      </div>

      {/* Report Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-8">

        <div className="bg-white p-6 rounded-xl border shadow-sm">
          <p className="text-sm text-gray-500">
            Employee Report
          </p>

          <h2 className="text-3xl font-bold text-gray-800 mt-2">
            120
          </h2>

          <p className="text-sm text-gray-500 mt-2">
            Total employees
          </p>
        </div>

        <div className="bg-white p-6 rounded-xl border shadow-sm">
          <p className="text-sm text-gray-500">
            Attendance Report
          </p>

          <h2 className="text-3xl font-bold text-gray-800 mt-2">
            87.5%
          </h2>

          <p className="text-sm text-gray-500 mt-2">
            Monthly attendance
          </p>
        </div>

        <div className="bg-white p-6 rounded-xl border shadow-sm">
          <p className="text-sm text-gray-500">
            Leave Report
          </p>

          <h2 className="text-3xl font-bold text-gray-800 mt-2">
            25
          </h2>

          <p className="text-sm text-gray-500 mt-2">
            Leave requests
          </p>
        </div>

        <div className="bg-white p-6 rounded-xl border shadow-sm">
          <p className="text-sm text-gray-500">
            Departments
          </p>

          <h2 className="text-3xl font-bold text-gray-800 mt-2">
            6
          </h2>

          <p className="text-sm text-gray-500 mt-2">
            Active departments
          </p>
        </div>

      </div>

      {/* Generate Reports */}
      <div className="bg-white rounded-xl border shadow-sm mt-8">

        <div className="p-6 border-b">
          <h2 className="text-xl font-semibold text-gray-800">
            Generate Report
          </h2>

          <p className="text-sm text-gray-500 mt-1">
            Select a report type and date range
          </p>
        </div>

        <div className="p-6">

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

            <div>
              <label className="block text-sm font-medium text-gray-700">
                Report Type
              </label>

              <select className="w-full mt-2 border rounded-lg px-4 py-3">
                <option>Employee Report</option>
                <option>Attendance Report</option>
                <option>Leave Report</option>
                <option>Department Report</option>
                <option>Designation Report</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700">
                From Date
              </label>

              <input
                type="date"
                className="w-full mt-2 border rounded-lg px-4 py-3"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700">
                To Date
              </label>

              <input
                type="date"
                className="w-full mt-2 border rounded-lg px-4 py-3"
              />
            </div>

          </div>

          <div className="mt-6 flex gap-3">

            <button className="bg-blue-600 text-white px-5 py-3 rounded-lg hover:bg-blue-700">
              Generate Report
            </button>

            <button className="border border-gray-300 px-5 py-3 rounded-lg hover:bg-gray-50">
              Export
            </button>

          </div>

        </div>

      </div>

      {/* Recent Reports */}
      <div className="bg-white rounded-xl border shadow-sm mt-8">

        <div className="p-6 border-b">
          <h2 className="text-xl font-semibold text-gray-800">
            Recent Reports
          </h2>
        </div>

        <div className="overflow-x-auto">

          <table className="w-full">

            <thead className="bg-gray-50">
              <tr>
                <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">
                  Report
                </th>

                <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">
                  Date
                </th>

                <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">
                  Generated By
                </th>

                <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">
                  Action
                </th>
              </tr>
            </thead>

            <tbody className="divide-y">

              <tr>
                <td className="px-6 py-4">
                  Employee Report
                </td>

                <td className="px-6 py-4 text-gray-500">
                  04 Sep 2026
                </td>

                <td className="px-6 py-4">
                  Admin User
                </td>

                <td className="px-6 py-4">
                  <button className="text-blue-600 hover:underline">
                    View
                  </button>
                </td>
              </tr>

              <tr>
                <td className="px-6 py-4">
                  Attendance Report
                </td>

                <td className="px-6 py-4 text-gray-500">
                  03 Sep 2026
                </td>

                <td className="px-6 py-4">
                  Admin User
                </td>

                <td className="px-6 py-4">
                  <button className="text-blue-600 hover:underline">
                    View
                  </button>
                </td>
              </tr>

              <tr>
                <td className="px-6 py-4">
                  Leave Report
                </td>

                <td className="px-6 py-4 text-gray-500">
                  02 Sep 2026
                </td>

                <td className="px-6 py-4">
                  Admin User
                </td>

                <td className="px-6 py-4">
                  <button className="text-blue-600 hover:underline">
                    View
                  </button>
                </td>
              </tr>

            </tbody>

          </table>

        </div>

      </div>

    </main>
  );
}